name: Build macOS App

on: [push]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install py2app
      - name: Build .app
        run: |
          py2applet --make-setup check_sites.py
          python setup.py py2app
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: YourApp
          path: dist/check_sites.app
